# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "afeadb3cb91e416fab8c4037e28d7456"
name = "test-app-new"
handle = "test-app-new-31"
application_url = "https://avg-bishop-expanded-differently.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-78532040.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://avg-bishop-expanded-differently.trycloudflare.com/auth/callback",
  "https://avg-bishop-expanded-differently.trycloudflare.com/auth/shopify/callback",
  "https://avg-bishop-expanded-differently.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
