# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef530ecc967ab49ccf860327e109593a"
name = "affiliate"
handle = "affiliate-52"
application_url = "https://bali-tri-india-airports.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-75138e4a.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://bali-tri-india-airports.trycloudflare.com/auth/callback",
  "https://bali-tri-india-airports.trycloudflare.com/auth/shopify/callback",
  "https://bali-tri-india-airports.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
